# tasks file for win-keepass
- name: Starte PSADT silent Uninstall
  win_shell: |
    & "{{ package_source_path }}\Deploy-Application.ps1" `
      -DeploymentType Uninstall `
      -DeployMode Silent
  register: deploy_result
  failed_when: deploy_result.rc not in [0, 3010]