# tasks file for win-hpcmsl
- name: Starte PSADT silent Uninstall
  win_shell: |
    & "{{ package_source_path }}\Invoke-AppDeployToolkit.exe" `
      -DeploymentType Uninstall `
      -DeployMode Silent
  register: deploy_result
  failed_when: deploy_result.rc not in [0, 3010]