# tasks file for win-notepadd++
- name: Start silent repair
  win_shell: |
    & "{{ package_source_path }}\Deploy-Application.ps1" `
      -DeploymentType Repair `
      -DeployMode Silent
  register: deploy_result
  failed_when: deploy_result.rc not in [0, 3010]